### ISSUE TITLE
PIP: No matching distribution found for dcgpy

### ISSUE THREAD

**Issue by BernardoGO** [darioizzo/d-CGP#20]
I've tried to install `dcgpy` and `pyaudi` from both pip2.7 and pip3.
Both of them threw the same error:
```

[bernardo@sager-pc Downloads]$ sudo pip install dcgpy
Collecting dcgpy
  Could not find a version that satisfies the requirement dcgpy (from versions: )
No matching distribution found for dcgpy
```

```
[bernardo@sager-pc Downloads]$ sudo pip2 install pyaudi
Collecting pyaudi
  Could not find a version that satisfies the requirement pyaudi (from versions: )
No matching distribution found for pyaudi

```

**Comment by darioizzo** [comment]
The list of supported architectures is here: https://pypi.python.org/pypi/dcgpy/1.0.1
you may have an unsupported architecture

**Comment by BernardoGO** [comment]
Not really.

I've tried installing dcgpy-1.0.1-cp27-cp27m-manylinux1_x86_64.whl on Ubuntu running on a i7 with python 2.7.

**Comment by cyclecycle** [comment]
Same problem here on this system:

```
uname -a
Linux nick-HP-EliteBook-8470p 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by darioizzo** [comment]
@graemedatanerds The link above details the currently available packages (from pypi). As you can see py36 is not there. That's why you are unable to install dcgpy using pip. Compiling is the only way right now to get it in your architecture

**Comment by graemedatanerds** [comment]
Of course! Monday morning derp, sorry if that came off snippy! Thanks for the quick response.

**Comment by 0x0L** [comment]
@darioizzo 
I really want to give this a shot but compiling in my corporate env (win machine with no visual studio no admin rights only conda) is just too painful :(
It would be nice if you could release a set of updated packages to pypi including windows and py36/37

**Comment by darioizzo** [comment]
I am currently working on the release of dcgp 1.1 with packages for Win64 Linux and OSx.
PY37 will be supported via PyPi (```pip install```), for ```conda install```, instead, only py 36 will be supported for the time being.

I will let you know when the packages are online (should be next week if all goes well)

**Comment by 0x0L** [comment]
@darioizzo Thanks! It works fine on my windows machine with py36
