### ISSUE TITLE
expression.simplify return only one output

### ISSUE THREAD

**Issue by darioizzo** [darioizzo/d-CGP#9]
At the moment the following code:
```python
dCGP = expression(inputs=1, outputs=2, rows=1, cols=15, levels_back=16, arity=2, kernels=kernels, seed = 13)
print("Simplified expression: ", dCGP.simplify(["x"]))
```
returns only the simplified expression corresponding to the first output node. It should, instead, return a list of symbolic simplified expression (one per output node). This would also be consistent with the return type of the call operator.

**Comment by Yawgmoth90** [comment]
Closed as solved
